# GitHub Actions Workflow for jDisco Library Build
#
# This file is an EXAMPLE workflow configuration for jDisco.
# To use this workflow:
#   1. Create .github/workflows/ directory in your repository root
#   2. Copy this file to .github/workflows/build.yml
#   3. Commit and push to trigger the workflow
#
# This workflow:
#   - Builds jDisco library with JDK 11 (compiles to Java 6 bytecode)
#   - Runs all JUnit tests
#   - Extracts build artifacts (JARs)
#   - Uploads artifacts for download (90-day retention)
#   - Uses BuildKit for optimal Docker layer caching
#

name: Build jDisco Library

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Allow manual trigger

# Cancel in-progress runs for same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # =============================================================================
  # Job 1: Build and Test with Docker
  # =============================================================================
  build-docker:
    name: Build with Docker (JDK 11)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Build jDisco (builder stage)
        run: |
          docker compose -f docker-compose.temurin.yml build builder

      - name: Run tests
        run: |
          docker compose -f docker-compose.temurin.yml run --rm dev mvn test

      - name: Extract artifacts
        run: |
          docker compose -f docker-compose.temurin.yml up artifact
          ls -lh artifacts/

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jdisco-jars
          path: |
            artifacts/*.jar
          retention-days: 90
          if-no-files-found: error

      - name: Display artifact info
        run: |
          echo "=== Build Artifacts ==="
          ls -lh artifacts/
          echo ""
          echo "=== JAR Contents ==="
          unzip -l artifacts/jdisco-1.2.0.jar | head -20

  # =============================================================================
  # Job 2: Build with Maven (Native - Alternative)
  # =============================================================================
  build-maven:
    name: Build with Maven (JDK 11)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and test with Maven
        run: |
          mvn clean install -B -V
        working-directory: .

      - name: Display test results
        if: always()
        run: |
          if [ -d target/surefire-reports ]; then
            echo "=== Test Results ==="
            cat target/surefire-reports/*.txt || true
          fi

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jdisco-jars-maven
          path: |
            target/*.jar
          retention-days: 90
          if-no-files-found: error

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/**
          retention-days: 30
          if-no-files-found: warn

  # =============================================================================
  # Job 3: Verify Java 6 Compatibility
  # =============================================================================
  verify-compatibility:
    name: Verify Java 6 Bytecode
    runs-on: ubuntu-latest
    needs: [build-docker]
    timeout-minutes: 5

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: jdisco-jars
          path: artifacts/

      - name: Verify bytecode version
        run: |
          # Extract class files and check bytecode version
          # Java 6 = version 50.0
          unzip -q artifacts/jdisco-1.2.0.jar -d extracted/

          # Check first few class files
          for classfile in $(find extracted/ -name "*.class" | head -5); do
            echo "Checking $classfile"
            # Extract bytecode version (major version in bytes 7-8)
            VERSION=$(od -An -t u1 -j 7 -N 1 "$classfile" | tr -d ' ')
            if [ "$VERSION" != "50" ]; then
              echo "ERROR: Class file not compiled for Java 6 (version: $VERSION, expected: 50)"
              exit 1
            fi
          done

          echo "SUCCESS: All checked class files are Java 6 compatible (version 50.0)"

  # =============================================================================
  # Job 4: Build Multi-Platform Images (Optional)
  # =============================================================================
  build-multiplatform:
    name: Build Multi-Platform Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build for linux/amd64 and linux/arm64
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --target artifact \
            -f Dockerfile.temurin \
            -t jdisco:artifact \
            .

  # =============================================================================
  # Job 5: Release (Only on Tags)
  # =============================================================================
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-docker, verify-compatibility]
    if: startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 10

    permissions:
      contents: write  # Required for creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: jdisco-jars
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.jar
          body: |
            ## jDisco ${{ github.ref_name }}

            Discrete-event and continuous simulation library for Java.

            ### Build Information
            - Compiled with: JDK 11
            - Target compatibility: Java 6
            - Build date: ${{ github.event.head_commit.timestamp }}

            ### Artifacts
            - `jdisco-1.2.0.jar` - Main library
            - `jdisco-1.2.0-sources.jar` - Source code
            - `jdisco-1.2.0-javadoc.jar` - API documentation

            ### Maven Coordinates
            ```xml
            <dependency>
                <groupId>dk.ruc.keld</groupId>
                <artifactId>jdisco</artifactId>
                <version>1.2.0</version>
            </dependency>
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# =============================================================================
# Workflow Summary
# =============================================================================
# This workflow provides:
#   ✅ Docker-based builds (reproducible, consistent)
#   ✅ Native Maven builds (faster, uses GitHub cache)
#   ✅ Java 6 bytecode verification
#   ✅ Multi-platform support (amd64, arm64)
#   ✅ Automatic releases on version tags
#   ✅ Artifact retention (90 days for JARs, 30 days for test results)
#   ✅ Concurrent build cancellation (saves CI minutes)
#   ✅ Test result uploads (always, even on failure)
#
# Choose the job that fits your needs:
#   - build-docker: Use Docker for consistency across environments
#   - build-maven: Use native Maven for speed and GitHub cache
#   - Both: Run both to verify consistency
